### ISSUE TITLE
No valid exports main found for '{project-path}/node_modules/@rollup/plugin-node-resolve'

### ISSUE THREAD

**Issue by evoactivity** [srowhani/ember-artisans#10]
After installing ember-artisans I receive this error trying to serve/build my app.
`No valid exports main found for '{project-path}/node_modules/@rollup/plugin-node-resolve'`

```
DEBUG: -------------------------------
DEBUG: Ember             : 3.18.1
DEBUG: Ember Data        : 3.18.0
DEBUG: Ember Postcss     : 6.0.1
DEBUG: Ember Simple Auth : 3.0.0
DEBUG: -------------------------------
```

**Comment by srowhani** [comment]
Strange... Which version of ember-artisans are you using? Could you also verify that plugin-node-resolve is in your node_modules directory?

**Comment by srowhani** [comment]
Try updating to node version 14... I've seen this issue in several other repos as well. Let me know if that fixes this.

**Comment by evoactivity** [comment]
Thanks. Updating node resolved it. Using v1.2.3 for reference.

**Comment by srowhani** [comment]
Cool! Glad it's working. I'll mark this one as closed for now!
