### ISSUE TITLE
How to import things in a worker.js file?

### ISSUE THREAD

**Issue by JonnoFTW** [srowhani/ember-artisans#2]
I would like to use a third party library (specifically [lz4js](https://github.com/Benzinga/lz4js)) in my worker script. The readme mentions that this is not possible, but we can use importScripts. Is there an example of how to do this?

I'm trying to do something like this:

```js
import { compress } from 'lz4js';

module.exports = {
  async doCompress(fileData) {
    return compress(new Uint8Array(fileData));
  },
}
```

Which is impossible because the worker can't import anything, getting the error:

```
compress.js:4 Uncaught SyntaxError: Cannot use import statement outside a module
```

**Comment by srowhani** [comment]
This isn't currently possible, but I'm looking into this. It's a very reasonable ask, so I'll see if I can get this to work!

**Comment by srowhani** [comment]
This should be working now. Give it a try, and let me know! Feel free to reopen if there's any issues, and we can track them here

**Comment by JonnoFTW** [comment]
Worked for me! Sending a 130mb to the worker and compressed result back worked just fine! I should probably mention that the computation result is actually in the `result` field of the returned object:

```js
        this.worker.compress(fileData).then(result => {
          console.log(result);
          if(result.error) {
            throw result.error;
          }
          const compressedData = result.result;
          const ratio = compressedData.length / oldLength * 100;
          console.log(`Compressed ${oldLength} to ${compressedData.length} (${ratio}% of original)`);
        }, err => {
          console.err(err);
        });
```

With worker:

```js
import { compress as lz4compress} from 'lz4js';

/**
 * Add your worker description here.
 */
export default class CompressWorker {
  compress(data) {
    return lz4compress(new Uint8Array(data));
  }
}
```

**Comment by srowhani** [comment]
Right... I was debating instead having the worker return result directly, instead of the node style "error" way of handling. Glad it's working for you now! 😄
